#!/usr/bin/env node
/* ============================================================
   TourForChild — build.js  (Node, no dependencies)
   Reads:  data/_master.json  +  data/raw/<id>.json  (one per city)
   Writes: data/index.js                 (window.TFC_INDEX — nav + search)
           data/cities/<countryCode>.js  (window.TFC_CITY_DATA[code] — full content, lazy-loaded)
           c/<lang>/<id>.html            (pre-rendered pages for Google / AI crawlers)
           sitemap.xml, robots.txt
   Run:    node build.js
   ============================================================ */
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const DATA = path.join(ROOT, "data");
const RAW = path.join(DATA, "raw");
const CITIES_DIR = path.join(DATA, "cities");
const SITE_ORIGIN = process.env.TFC_ORIGIN || "https://tourforchild.example"; // set real domain before deploy
const LANGS = ["ko", "en", "ja", "zh"];

function readJSON(p, fallback) {
  try { return JSON.parse(fs.readFileSync(p, "utf8")); }
  catch (e) { return fallback; }
}
function pick(obj, en) {
  // ensure a {ko,en,ja,zh} object; fall back to English string for missing langs
  const o = {};
  LANGS.forEach(l => { o[l] = (obj && obj[l]) || (obj && obj.en) || en || ""; });
  return o;
}
function esc(s) {
  return String(s == null ? "" : s).replace(/[&<>"]/g, c =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

const master = readJSON(path.join(DATA, "_master.json"), { countries: {}, cities: [] });
const countries = master.countries || {};
const cityRows = master.cities || [];

const I18N = { /* minimal labels for pre-rendered pages */
  ko: { facts: "이런 사실 알고 있었어?", story: "이야기", places: "가볼 만한 곳", back: "TourForChild 홈", fix: "정보 수정 요청" },
  en: { facts: "Did you know?", story: "The Story", places: "Places to visit", back: "TourForChild home", fix: "Suggest a correction" },
  ja: { facts: "知ってた？", story: "ものがたり", places: "行きたい場所", back: "TourForChild ホーム", fix: "情報の修正依頼" },
  zh: { facts: "你知道吗？", story: "故事", places: "值得一去的地方", back: "TourForChild 首页", fix: "建议更正" }
};

// ---- assemble ----
const indexCities = [];
const byCountry = {};       // code -> { id -> fullContent }
const countryCityIds = {};  // code -> [ids]
let withContent = 0;

for (const row of cityRows) {
  const raw = readJSON(path.join(RAW, row.id + ".json"), null);
  const hasContent = !!raw;
  if (hasContent) withContent++;

  const name = pick(raw && raw.name, row.en);
  const tagline = pick(raw && raw.tagline, "");
  const coords = (raw && Array.isArray(raw.coords)) ? raw.coords : null;

  indexCities.push({
    id: row.id, country: row.country, emoji: row.emoji || "📍",
    featured: !!row.featured, name, tagline, coords
  });

  (countryCityIds[row.country] = countryCityIds[row.country] || []).push(row.id);

  if (hasContent) {
    (byCountry[row.country] = byCountry[row.country] || {})[row.id] = {
      name, tagline, coords,
      story: {
        ko: (raw.story && raw.story.ko) || (raw.intro ? [raw.intro.ko || raw.intro.en] : []),
        en: (raw.story && raw.story.en) || (raw.intro ? [raw.intro.en] : []),
        ja: (raw.story && raw.story.ja) || (raw.intro ? [raw.intro.ja || raw.intro.en] : []),
        zh: (raw.story && raw.story.zh) || (raw.intro ? [raw.intro.zh || raw.intro.en] : [])
      },
      funFacts: {
        ko: (raw.funFacts && raw.funFacts.ko) || [],
        en: (raw.funFacts && raw.funFacts.en) || [],
        ja: (raw.funFacts && raw.funFacts.ja) || [],
        zh: (raw.funFacts && raw.funFacts.zh) || []
      },
      kidQuestion: pick(raw.kidQuestion, ""),
      places: (raw.places || []).map(p => ({
        name: pick(p.name, ""), blurb: pick(p.blurb, ""),
        coords: Array.isArray(p.coords) ? p.coords : null
      }))
    };
  }
}

// index countries (only those that have cities)
const indexCountries = Object.keys(countries)
  .filter(code => countryCityIds[code] && countryCityIds[code].length)
  .map(code => ({
    code, continent: countries[code].continent, flag: countries[code].flag,
    name: countries[code].name, cityIds: countryCityIds[code]
  }));

// ---- write data/index.js ----
fs.mkdirSync(CITIES_DIR, { recursive: true });
const indexObj = { countries: indexCountries, cities: indexCities };
fs.writeFileSync(path.join(DATA, "index.js"),
  "/* AUTO-GENERATED by build.js — do not edit by hand */\n" +
  "window.TFC_INDEX = " + JSON.stringify(indexObj) + ";\n", "utf8");

// ---- write data/cities/<code>.js ----
let countryFiles = 0;
for (const code of Object.keys(byCountry)) {
  const body = "/* AUTO-GENERATED by build.js */\n" +
    "(window.TFC_CITY_DATA=window.TFC_CITY_DATA||{})[" + JSON.stringify(code) + "]=" +
    JSON.stringify(byCountry[code]) + ";\n";
  fs.writeFileSync(path.join(CITIES_DIR, code + ".js"), body, "utf8");
  countryFiles++;
}

// ---- pre-rendered SEO pages: c/<lang>/<id>.html ----
const sitemapUrls = [SITE_ORIGIN + "/"];
let pages = 0;
for (const row of cityRows) {
  const full = byCountry[row.country] && byCountry[row.country][row.id];
  if (!full) continue; // only pages for cities with content
  const country = countries[row.country] || { name: pick(null, row.country), flag: "" };
  for (const lang of LANGS) {
    const dir = path.join(ROOT, "c", lang);
    fs.mkdirSync(dir, { recursive: true });
    const url = SITE_ORIGIN + "/c/" + lang + "/" + row.id + ".html";
    const alternates = LANGS.map(l =>
      `<link rel="alternate" hreflang="${l}" href="${SITE_ORIGIN}/c/${l}/${row.id}.html">`).join("\n  ") +
      `\n  <link rel="alternate" hreflang="x-default" href="${SITE_ORIGIN}/c/en/${row.id}.html">`;
    const cityName = full.name[lang], tagline = full.tagline[lang];
    const story = (full.story && full.story[lang]) || [];
    const intro = story[0] || "";
    const facts = (full.funFacts[lang] || []);
    const places = full.places || [];
    const jsonld = {
      "@context": "https://schema.org", "@type": "TouristDestination",
      name: cityName, description: tagline || intro,
      address: { "@type": "PostalAddress", addressCountry: country.name[lang] || country.name.en }
    };
    if (full.coords) jsonld.geo = { "@type": "GeoCoordinates", latitude: full.coords[0], longitude: full.coords[1] };

    const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(cityName)} — TourForChild</title>
<meta name="description" content="${esc(tagline || intro)}">
<link rel="canonical" href="${url}">
${alternates}
<meta property="og:title" content="${esc(cityName)} — TourForChild">
<meta property="og:description" content="${esc(tagline || intro)}">
<meta name="theme-color" content="#ff6b6b">
<link rel="manifest" href="../../manifest.webmanifest">
<link rel="icon" href="../../icon.svg">
<link rel="apple-touch-icon" href="../../icon.svg">
<link rel="stylesheet" href="../../styles.css">
<script type="application/ld+json">${JSON.stringify(jsonld)}</script>
</head>
<body>
<header class="site-header"><div class="header-inner">
  <a class="logo" href="../../index.html#/"><span class="globe">🌍</span><span class="full"><b>Tour</b><i>ForChild</i></span></a>
</div></header>
<main class="wrap">
  <div class="city-hero"><span class="bg-emoji">${row.emoji}</span>
    <div class="crumbs">${esc(country.flag + " " + (country.name[lang] || country.name.en))}</div>
    <h1><span class="emoji">${row.emoji}</span> ${esc(cityName)}</h1>
    <div class="tagline">${esc(tagline)}</div>
  </div>
  ${story.length ? `<div class="block"><h2>📖 ${esc(I18N[lang].story)}</h2>${story.map(p => `<p class="intro-text">${esc(p)}</p>`).join("")}</div>` : ""}
  ${facts.length ? `<div class="block"><h2>🤩 ${esc(I18N[lang].facts)}</h2><ul class="facts">${
      facts.map((f, i) => `<li><span class="n">${i + 1}</span><span>${esc(f)}</span></li>`).join("")
    }</ul></div>` : ""}
  ${places.length ? `<div class="block"><h2>📍 ${esc(I18N[lang].places)}</h2><div class="places">${
      places.map(p => `<div class="place"><h4>📍 ${esc(p.name[lang])}</h4><p>${esc(p.blurb[lang])}</p></div>`).join("")
    }</div></div>` : ""}
  <p style="margin-top:20px"><a class="btn" href="../../index.html#/city/${row.id}">✨ ${esc(I18N[lang].back)} →</a></p>
</main>
<footer class="site-footer"><div class="footer-inner">
  <p><a href="mailto:hoonjeong.eden@gmail.com?subject=TourForChild%20${row.id}">${esc(I18N[lang].fix)}</a></p>
  <p>© TourForChild · Maps © OpenStreetMap contributors</p>
</div></footer>
</body>
</html>`;
    fs.writeFileSync(path.join(dir, row.id + ".html"), html, "utf8");
    sitemapUrls.push(url);
    pages++;
  }
}

// ---- sitemap.xml + robots.txt ----
fs.writeFileSync(path.join(ROOT, "sitemap.xml"),
  '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  sitemapUrls.map(u => "  <url><loc>" + esc(u) + "</loc></url>").join("\n") +
  "\n</urlset>\n", "utf8");
fs.writeFileSync(path.join(ROOT, "robots.txt"),
  "User-agent: *\nAllow: /\nSitemap: " + SITE_ORIGIN + "/sitemap.xml\n", "utf8");

console.log("✅ build complete");
console.log("   cities in master : " + cityRows.length);
console.log("   with content     : " + withContent);
console.log("   country files    : " + countryFiles);
console.log("   SEO pages        : " + pages);
console.log("   (set real domain via TFC_ORIGIN env before deploying for correct sitemap URLs)");
